name: Deploy Flutter Web to FTP (Integrator)

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'          # Só roda se houver alterações em arquivos dentro de lib/
      - 'assets/**'       # Ou se houver alterações na pasta assets/
      # Adicione outras pastas ou arquivos conforme necessário

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web
          server-dir: /public_html/
